courses/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static 


urlpatterns = [
    path('sections/handout/create/', add_new_section_choices),
    path('handouts/', handout_sections),
    path('handout/detail/section/', all_handouts),
    path('handouts_detail/', handout_detail),
    path('faq/', faq_list),
    path('faq/detail/section/', faq),
    path('data/handout/content/', HandoutApiView.as_view()),
    path('data/handout/content/<int:pk>/', HandoutUpdateApiView.as_view()),
    path('data/Faq/content/', FaqApiView.as_view()),
    path('data/Faq/content/<int:pk>/', FaqUpdateApiView.as_view()),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 
from django.conf import settings
urlpatterns = [
    path('auth/super_admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',include('users.urls')),
    path('',include('notifications.urls')),
    path('',include('gallery.urls')),
    path('',include('shopping.urls')),
    path('',include('courses.urls')),
    path('',include('pictures.urls'))
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views
from django.urls import path
from django.contrib.auth.views import PasswordChangeDoneView,PasswordChangeView
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"

urlpatterns = [
    path('',home, name="home"),
    path('home/',home),
    path('login/',login, name="login"),
    path('auth/admin/',admin, name="admin-lte"),
    path('auth/user/user_info/',user_information),
    path('auth/user/user_info/edit/<int:pk>',edit_info.as_view()),
    path('data/User/content/' , UserApiView.as_view()),
    path('data/User/content/<int:pk>/' , UserUpdateApiView.as_view()),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Notification
urlpatterns += [
    path('Notification/create/', NotificationCreate.as_view(), name="notification-create"),
    path('Notification/List/', NotificationList.as_view(), name="notification-list"),
    path('Notification/Update/<int:pk>', NotificationUpdate.as_view(), name="notification-update"),
    path('Notification/Delet/<int:pk>', NotificationDelet.as_view(), name="notification-delet"),
]

# Circular
urlpatterns += [
    path('Circular/create/', CircularCreate.as_view(), name="Circular-create"),
    path('Circular/List/', CircularList.as_view(), name="Circular-list"),
    path('Circular/Update/<int:pk>', CircularUpdate.as_view(), name="Circular-update"),
    path('Circular/Delet/<int:pk>', CircularDelet.as_view(), name="Circular-delet"),
    
]

# Works

urlpatterns += [
    path('Works/create/', WorksCreate.as_view(), name="Works-create"),
    path('Works/List/', WorksList.as_view(), name="Works-list"),
    path('Works/Update/<int:pk>', WorksUpdate.as_view(), name="Works-update"),
    path('Works/Delet/<int:pk>', WorksDelet.as_view(), name="Works-delet"),
    
]

# Users

urlpatterns += [
    path('User/create/', UserCreate.as_view(), name="User-create"),
    path('User/List/', UserList.as_view(), name="User-list"),
    path('User/Update/<int:pk>', UserUpdate.as_view(), name="User-update"),
    path('User/Delet/<int:pk>', UserDelet.as_view(), name="User-delet"),
    path("logout/", views.LogoutView.as_view(), name="logout")
    
]

urlpatterns += [
    path('password_change/<int:pk>',password_recovery,name='password_change'),
    path('password_change/done/',password_change_done,name='password_change_done'),

]

# gallery

urlpatterns += [
    path('Gallery/images/WorkList/' , Work_Image_List.as_view() , name='Work_Image-List'),
    path('Gallery/images/CircularList/',Circular_Images_List.as_view() , name='Circular_Image-List')
]


# faq 

urlpatterns += [
    path('faq/List/', faqlist.as_view(), name="faq-list"),
    path('faq/create/', FaqCreate.as_view(), name="faq-create"),
    path('faq/Update/<int:pk>', faqUpdate.as_view(), name="faq-update"),
    path('faq/Delet/<int:pk>', faqDelet.as_view(), name="faq-delet")
]

# Handout


urlpatterns += [
    path('Handout/List/', HandoutList.as_view(), name="Handout-list"),
    path('Handout/create/', HandoutCreate.as_view(), name="Handout-create"),
    path('Handout/Update/<int:pk>', HandoutUpdate.as_view(), name="Handout-update"),
    path('Handout/Delet/<int:pk>', HandoutDelet.as_view(), name="Handout-delet")
]

# SectionChoice 

urlpatterns += [
    path('sectionchoice/List/', SectionChoice_list.as_view(), name="sectionchoice-list"),
    path('sectionchoice/Delete/<int:pk>', SectionChoice_Delet.as_view(), name="sectionchoice-delete")
]

urlpatterns += [
    path('picture/create/' , create_picture.as_view(),name="picture-create"),
    path('picture/list/' , picture_list.as_view(),name="picture-list"),
    path('picture/delete/<int:pk>' , delete_picture.as_view(),name="picture-delete"),
    
]

urlpatterns += [
    path('HomeInfo/List/', HomeInfoList.as_view(), name="HomeInfo-list"),
    path('HomeInfo/create/', HomeInfoCreate.as_view(), name="HomeInfo-create"),
    path('HomeInfo/Update/<int:pk>', HomeInfoUpdate.as_view(), name="HomeInfo-update"),
    path('HomeInfo/Delet/<int:pk>', HomeInfoDelet.as_view(), name="HomeInfo-delet")
]

courses/models.py
from django.db import models
from extensions.utils import jalali_converter
from ckeditor_uploader.fields import RichTextUploadingField


class SectionChoice(models.Model):
    value = models.CharField(max_length=100 , verbose_name='کلید دسترسی به رشته',blank=False, null=False)
    display_text = models.CharField(max_length=100 , verbose_name='نام رشته', blank=False, null=False)

    def __str__(self):
         return self.display_text
    class Meta:
        verbose_name = 'رشته'
        verbose_name_plural = 'رشته ها'

class IP_Address(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name="ادرس ای پی ")


class Faq(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش‌نویس'),
        ('p', "منتشر شده"),
    )
    question = models.CharField(max_length=500 , verbose_name='سوال')
    awnser = RichTextUploadingField(verbose_name='جواب')
    lesson_sections = models.CharField(max_length=500,verbose_name='درس',blank=False , null=False , default='')
    section = models.ForeignKey(SectionChoice , on_delete=models.CASCADE, verbose_name='رشته',default=None)
    create_by = models.CharField(max_length=200 , blank=False , null=False , default=None,verbose_name='نام ناشر')
    create_time = models.DateTimeField(auto_now_add=True,verbose_name='تاریخ ساخت')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d', verbose_name="وضعیت")
    
    
    class Meta:
        db_table = 'faq'
        verbose_name = 'پرسش و پاسخ'
        verbose_name_plural = 'پرسش و پاسخ ها'

    def jpublish(self):
	    return jalali_converter(self.create_time)
    jpublish.short_description = 'زمان انتشار'
    
    def __str__(self):
        return '{}---{}'.format(self.pk , self.question)
    
    
class Handout(models.Model):
    STATUS_CHOICES = (
        ('d', 'پیش‌نویس'),
        ('p', "منتشر شده"),
    )


    title = models.CharField(max_length=200,verbose_name='عنوان جزوه')
    file = models.FileField(upload_to='docs/' ,default=None , verbose_name='فایل جزوه')
    create_time = models.DateTimeField(auto_now_add=True,verbose_name='تاریخ ساخت')
    section = models.ForeignKey(SectionChoice,on_delete=models.CASCADE,max_length=150  , verbose_name='رشته' , blank=False , null=False)
    lesson = models.CharField(max_length=100  , verbose_name='درس' , blank=False , null=False)
    create_by = models.CharField(max_length=200 ,default= None, verbose_name='نام هنرآموز',null=False,blank=False)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='d', verbose_name="وضعیت")
    visits = models.ManyToManyField(IP_Address, blank=True, related_name="visits", verbose_name="بازدید ها")


        
    
    class Meta:
        db_table = 'handout'
        verbose_name = 'جزوه'
        verbose_name_plural = 'جزوه ها'
    
    
    def jpublish(self):
	    return jalali_converter(self.create_time)
    jpublish.short_description = 'زمان انتشار'

    
    def __str__(self):
        return '{}---{}'.format(self.pk , self.title)
    
    
class File(models.Model):
    post = models.ForeignKey(Handout , on_delete= models.CASCADE , related_name='other_files' )
    other_files = models.FileField(upload_to='docs/' ,default=None , verbose_name='فایل های دیگر جزوه')
    def __str__(self):
        return self.other_files.url

courses/forms.py
from django import forms

class SearchForm(forms.Form):
    title = forms.CharField(max_length=100, required=False)
    
    
    
class Add_new_section_choicesForm(forms.Form):
    new_choice = forms.CharField(max_length=50, label='نام رشته جدید : ')

courses/views.py
from django.shortcuts import render , redirect
from django.http import Http404 , HttpResponseForbidden
from .models import *
from .forms import *
from django.shortcuts import get_object_or_404
from .serializers import *
from rest_framework.decorators import api_view , permission_classes
from rest_framework.permissions import IsAuthenticated , IsAdminUser
from rest_framework.response import Response
from rest_framework.status import *
from rest_framework import generics
from rest_framework.exceptions import ParseError
from django.contrib import messages
from googletrans import Translator
from time import sleep


def handout_sections(request):
    handouts = SectionChoice.objects.all()
    return render(request , 'Handout.html' , {
        'handouts' : handouts
        })


def all_handouts(request):
    handout_section = request.GET.get('value')
    section_choice = SectionChoice.objects.get(value = handout_section)
    handouts = Handout.objects.filter(status = 'p', section = section_choice).order_by('-create_time')
    return render(request ,'hanout_choice.html' , {
        'handouts': handouts,
        'section': section_choice
    })
    
        
def handout_detail(request):
    
    pk = request.GET.get('pk')
    
    handout_detail = get_object_or_404(Handout,pk = pk)
    previous_url = request.META.get('HTTP_REFERER', None)
    if handout_detail.status != 'p':
        return HttpResponseForbidden()

    return render(request,'handout_detail.html',{
        'handout':handout_detail,
        'previous_url' : previous_url
        })


def faq_list(request):

    faqs = SectionChoice.objects.all()
    return render(request , 'faq_sections.html' , {
        'faqs' : faqs
        })


def faq(request):
    try:
        handout_section = request.GET.get('value')
        section_choice = SectionChoice.objects.get(value = handout_section)
        
        faq = Faq.objects.filter(status = 'p',section = section_choice).order_by('-create_time')
    except Faq.DoesNotExist:
        raise Http404('سوال و جوابی موجود نیست')
    return render(request , 'faq_list.html' , {
        'faq':faq,
        'section':section_choice
    })



class FaqApiView(generics.ListCreateAPIView):
    queryset = Faq.objects.all().order_by('-id')
    serializer_class = FaqSerializer
    permission_classes = [IsAuthenticated, IsAdminUser]


class FaqUpdateApiView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Faq.objects.all().order_by('-id')
    serializer_class = FaqSerializer
    permission_classes = [IsAuthenticated, IsAdminUser]

        
class HandoutApiView(generics.ListCreateAPIView):
    queryset = Handout.objects.all()
    serializer_class = HandoutSerializer
    permission_classes = [IsAuthenticated, IsAdminUser]


class HandoutUpdateApiView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Handout.objects.all()
    serializer_class = HandoutSerializer
    permission_classes = [IsAuthenticated, IsAdminUser]
   
        
        
def add_new_section_choices(request):
    if request.method == 'POST':
        form = Add_new_section_choicesForm(request.POST)
        if form.is_valid():
            value = 0
            new_choice = form.cleaned_data['new_choice']
            if SectionChoice.objects.last():
                value = SectionChoice.objects.last().pk + 1
            else:
                value = 1
            SectionChoice.objects.create(value = value,display_text = new_choice)
            return redirect('/sectionchoice/List/')
    
    else:
        form = Add_new_section_choicesForm()

    return render(request, 'handout_section_create.html', {
        'form': form,
    })

courses/templates/Handout.html
{%extends 'base.html'%}
{%load static%}
<!DOCTYPE html>
<html>
<head>
  {%block head%}
  <title>جزوه ها</title>
  <style>

	.product-item {
		margin-top: 20px;
		border: 1px solid #ddd;
		border-radius: 4px;
		padding: 15px;
		margin-bottom: 20px;
	}

	.product-image {
		max-width: 100%;
		height: auto;
		margin: 0!important;
	}

	.product-title {
		text-align: center;
		font-size: 18px;
		margin-top: 10px;
	}

	.product-description {
		margin-top: 5px;
		text-align: center;
	}

	.product-button {
		margin-top: 10px;
		width: 100%;
	}
</style>
{%endblock head%}
</head>
<body>
{%block content%}

    
	<section class="product-section">
		<div class="container">
            <div class="row">
                {% for handout in handouts %}
                <div class="col-md-4">
					<div class="product-item">
						<h4 class="product-title">جزوه های رشته ی {{handout.display_text}}</h4>
						<a href="/handout/detail/section/?value={{handout.value}}" class="btn btn-primary product-button">جزئیات</a>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</section>

    {%endblock content%}
</body>
</html>

courses/templates/faq_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>پرسش و پاسخ های رشته ی {{section}} </title>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

    <link rel="stylesheet" href="{%static 'fonts/icomoon/style.css'%}">

    <link rel="stylesheet" href="{%static 'css/owl.carousel.min.css'%}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    
    <!-- Style -->
    <link rel="stylesheet" href="{%static 'css/style.css'%}">
    <link rel="stylesheet" href=" {% static 'css/font-home.css' %} ">
	<style>
		.text-right {
			width: 100%;
		}
        .btn-link{
            text-decoration: none!important;
        }
        .rotate {
            transform: rotate(0deg);
            transition: transform 0.3s ease;
          }
        
          .collapsed  {
            transform: rotate(180deg);
          }
          
		  p{
			text-align: right;
			color: #362c2c;
			font-size: 19px;
		  }
          
          
	</style>
</head>
<body>
    <div class="site-mobile-menu site-navbar-target">
		<div class="site-mobile-menu-header">
		  <div class="site-mobile-menu-close mt-3">
			<span class="icon-close2 js-menu-toggle"></span>
		  </div>
		</div>
		<div class="site-mobile-menu-body"></div>
	  </div>
  
  
  
  
	  <header class="site-navbar js-sticky-header site-navbar-target" role="banner">
  
		<div class="container">
		  <div class="row align-items-center position-relative">
  
  
			<div class="site-logo">
			  <a href="/home/" class="text-black"><span class="text-primary">هنرستان خواجه نصیر</span></a>
			  
			</div>
			
			<div class="col-12">
			  <nav class="site-navigation text-right ml-auto " role="navigation">
				
				<ul class="site-menu main-menu js-clone-nav ml-auto d-none d-lg-block">
				  
				  
				  <li><a href="/auth/user/user_info/" class="nav-link">پنل کاربری</a></li>
				  
  
				  <li class="has-children">
					<a href="#" class="nav-link">بخش دروس</a>
					<ul class="dropdown arrow-top">
  
					  <li><a href="/handouts/">جزوه ها</a></li>
  
					  
						<li><a href="/faq/">پرسش و پاسخ ها</a></li>
						  
					  </ul>
					</li>
					  
					<li class="has-children">
					  <a href="#" class="nav-link">انتشاریه ها</a>
					<ul class="dropdown arrow-top">
					  <li><a href="/notifications/" class="nav-link">اطلاعیه ها</a></li>
					  <li><a href="/Works/" class="nav-link">نمونه کار ها</a></li>
					</ul>
				  </li>
				  
				  
				  <li><a href="/home/#infog" class="nav- link">تماس با ما</a></li>
				  
				</ul>
			  </nav>
  
			</div>
  
			<div class="toggle-button d-inline-block d-lg-none"><a href="#" class="site-menu-toggle py-5 js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>
  
		  </div>
		</div>
  
	  </header>  
    
	<section class="section py-5">
		<div class="container">
			<h2 class="section-heading text-right">پرسش و پاسخ ها</h2>
			<br>
			<div class="accordion" id="faqAccordion">
				{% for i in faq %}
        {% if i.status == 'p'%}
				<div class="card">
					<div class="card-header" id="heading-{{ i.pk }}">
						<h3 class="mb-0">
 
              <h5 style="width: 100%; text-align: center;">عنوان سوال : {{i.question}}</h5>
              <h5 style="width: 100%; text-align: center;">نام درس : {{i.lesson_sections}}</h5>
              <button class="btn btn-link text-center" type="button" data-toggle="collapse" data-target="#collapse-{{ i.pk }}" aria-expanded="true" aria-controls="collapse-{{ i.pk }}" style="width:100%;" onclick="toggleCollapse(this)">
                  <span class="icon-arrow-up rotate"></span>
                </button> 
                              
						</h3>
					</div>
					<div id="collapse-{{ i.pk }}" class="collapse show" aria-labelledby="heading-{{ i.pk }}" data-parent="#faqAccordion">
						<div class="card-body text-right">
							<h5>{{i.awnser | safe}}</h5>
							<br>
    						<h6>نام ناشر : {{i.create_by}}</h6>

						</div>
						
					</div>
				</div>
        {% endif %}
				{% endfor %}
			</div>
		</div>
	</section>

  <br><br>
  <div class="mt-5">
	<footer>
<p style="color: #b3b3b3!important; font-weight: 300; text-align: center;">تمامی حقوق مادی و معنوی مطالب برای صاحب سایت محفوظ است</p>
</footer>
</div>

	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
	<script>
		$(document).ready(function() {
		  $('.btn-link').click(function() {
		    $(this).find('.rotate').toggleClass('collapsed');
		    $(this).attr('aria-expanded', $(this).attr('aria-expanded') === 'false' ? 'true' : 'false');
		  });

		  $('.collapse').on('shown.bs.collapse', function() {
		    var $header = $(this).prev('.card-header');
		    $header.find('.rotate').removeClass('collapsed');
		    $header.find('.btn-link').attr('aria-expanded', 'true');
		  }).on('hidden.bs.collapse', function() {
		    var $header = $(this).prev('.card-header');
		    $header.find('.rotate').addClass('collapsed');
		    $header.find('.btn-link').attr('aria-expanded', 'false');
		  });

		  // بستن همه‌ی اجزای کشویی به صورت پیش‌فرض
		  $('.collapse').collapse('hide');
		});
	</script>
    <script>
        function toggleCollapse(button) {
          var collapse = button.getAttribute('data-target');
          var icon = button.querySelector('.rotate');
      
          if (collapse.classList.contains('show')) {
            icon.classList.remove('rotate');
          } else {
            icon.classList.add('rotate');
          }
      
          $(collapse).collapse('toggle');
        }
      </script>
      
      


      
      <script>
        $(document).ready(function() {
          // بستن همه‌ی منوها به صورت پیش‌فرض
          $('.collapse').collapse('hide');
        });
      </script>
</body>

</html>

courses/templates/faq_sections.html
{%extends 'base.html'%}
{%load static%}
<!DOCTYPE html>
<html>
<head>
  {%block head%}
  <title>پرسش و پاسخ ها</title>
  <style>

	.product-item {
		margin-top: 20px;
		border: 1px solid #ddd;
		border-radius: 4px;
		padding: 15px;
		margin-bottom: 20px;
	}

	.product-image {
		max-width: 100%;
		height: auto;
		margin: 0!important;
	}

	.product-title {
		text-align: center;
		font-size: 18px;
		margin-top: 10px;
	}

	.product-description {
		margin-top: 5px;
		text-align: center;
	}

	.product-button {
		margin-top: 10px;
		width: 100%;
	}
</style>
{%endblock head%}
</head>
<body>
{%block content%}

    
	<section class="product-section">
		<div class="container">
            <div class="row">
                {% for faq in faqs %}
                <div class="col-md-4">
					<div class="product-item">
						<h4 class="product-title">پرسش و پاسخ های رشته ی {{faq.display_text}}</h4>
						<a href="/faq/detail/section/?value={{faq.value}}" class="btn btn-primary product-button">جزئیات</a>
					</div>
				</div>
                {% endfor %}
			</div>
		</div>
	</section>

    {%endblock content%}
</body>
</html>

courses/templates/handout_detail.html
{%extends 'base.html'%}
{%load static%}

  
  {%block head%}
  <link rel="stylesheet" href=" {% static 'css/circulars_detail.css' %} ">
    <title>اطلاعات جزوه</title>
    {%endblock head%}
  </head>
<body>

    {%block content%}

    <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8">
            <div class="card mt-4 shadow-lg">
              <div class="card-body">
                <h3 class="card-title text-center text-primary">{{handout.title}}</h3>
                <h4 style="text-align: center;"><a href="{{handout.file.url}}" style="color: red;">دانلود فایل جزوه</a></h4>
                {% if handout.other_files.all %}
                <p style="text-align: center; margin-top: 10px; margin-bottom: 10px;"> : دیگر فایل های جزوه</p>
                {% for file in handout.other_files.all %}
                <h4 style="text-align: center;"><a href="{{file.other_files.url}}" style="color: red;">دانلود فایل جزوه</a></h4>
                {% endfor %}
                {% endif %}
                <p class="card-text text-center" style="margin-top: 20px;"><small class="text-muted">نام هنرآموز : {{handout.create_by}}</small></p>
                <p class="card-text text-center" style="margin-top: 10px;"><small class="text-muted">ساخته شده در تاریخ {{handout.jpublish}}</small></p>
                <a class="back btn btn-outline-danger" href="{{previous_url}}" style="margin-top: 20px;"> بازگشت </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>

      {%endblock content%}

courses/templates/handout_searched.html
{% extends 'base.html' %}
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}
<link rel="stylesheet" href=" {% static 'css/notifications_searched.css' %} ">
<link rel="stylesheet" href=" {% static 'css/rtl.css' %} ">
<title>نتایج جست و جو</title>
{% endblock head %}
</head>
<body>
  

{%block content%}
<a class="back btn btn-outline-danger " href="/handouts/"> بازگشت </a>

  {%for handout in handouts %}
  <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-8">
            <div class="card mt-4 shadow-lg">
              <div class="card-body">
                <h3 class="card-title text-center text-primary">{{handout.title}}</h3><br>
                <h4 style="text-align: center;"><a href="{{handout.file.url}}" style="color: red;">دانلود فایل جزوه</a></h4><br>
                <p class="card-text text-center"><small class="text-muted">ساخته شده در تاریخ {{handout.create_time}}</small></p>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {%endfor%}
    <br><br><br>
{%endblock content%}
</body>
</html>

courses/templates/handout_section_create.html
{% extends 'users/adminlte.html' %}
{% load crispy_forms_tags %}

{% block title %}افزودن رشته{% endblock %}


{% block content %}
    <div class="col-md-12">
        <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title mb-0 float-left">افزودن رشته جدید</h3>
        </div>
            <div class="card-body">
                {% if messages %}
                <ul class="messages">
                  {% for message in messages %}
                  <center class="alert {{ message.tags }}" role="alert">
                      {{ message }}
                  </center>
              {% endfor %}
                </ul>
                {% endif %}
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-6 ">
                            {{form.new_choice|as_crispy_field }}
                        </div>
                        <div style=" display: flex; align-items: center;">
                        <button class="btn btn-success">افزودن رشته جدید</button>
                        </div>
                    </div>
            </form>
    </div>

{% endblock %}

courses/templates/hanout_choice.html
{%extends 'base.html'%}
{%load static%}

{%block head%}
<title>جزوه های رشته ی {{section}}</title>
{%endblock head%}


{%block content%}

<main dir="rtl">

    <div class="search-container" dir="rtl">
        <form action="" method="POST">
            {%csrf_token%}
            <input type="text" name="title" id="id_title" maxlength="50" class="search-input form-control" placeholder="جست و جو بر اساس عنوان..."	required>
            <button type="submit" class="btn btn-outline-primary">جست وجو</button>
        </form>
    </div>
    
    {%for handout in handouts%}

    <article class="article">
    <h1>عنوان جزوه : {{handout.title|safe}}</h1><br>
    <h5 style="text-align: start;">نام درس : {{handout.lesson}}</h2>
    <h6>نام هنرآموز : {{handout.create_by}}</h6>
    <h6>تاریخ انتشار : {{handout.jpublish}}</h6>


    <a href="/handouts_detail/?pk={{handout.pk}}" class="post_deatiles btn btn-outline-primary">مشاهده اطلاعات کامل</a>
    </article>
    {%endfor%}
</main>
<br><br><br>
{% endblock content%}