project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static 
from django.conf import settings
urlpatterns = [
    path('auth/super_admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',include('users.urls')),
    path('',include('notifications.urls')),
    path('',include('gallery.urls')),
    path('',include('shopping.urls')),
    path('',include('courses.urls')),
    path('',include('pictures.urls'))
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views
from django.urls import path
from django.contrib.auth.views import PasswordChangeDoneView,PasswordChangeView
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = "users"

urlpatterns = [
    path('',home, name="home"),
    path('home/',home),
    path('login/',login, name="login"),
    path('auth/admin/',admin, name="admin-lte"),
    path('auth/user/user_info/',user_information),
    path('auth/user/user_info/edit/<int:pk>',edit_info.as_view()),
    path('data/User/content/' , UserApiView.as_view()),
    path('data/User/content/<int:pk>/' , UserUpdateApiView.as_view()),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Notification
urlpatterns += [
    path('Notification/create/', NotificationCreate.as_view(), name="notification-create"),
    path('Notification/List/', NotificationList.as_view(), name="notification-list"),
    path('Notification/Update/<int:pk>', NotificationUpdate.as_view(), name="notification-update"),
    path('Notification/Delet/<int:pk>', NotificationDelet.as_view(), name="notification-delet"),
]

# Circular
urlpatterns += [
    path('Circular/create/', CircularCreate.as_view(), name="Circular-create"),
    path('Circular/List/', CircularList.as_view(), name="Circular-list"),
    path('Circular/Update/<int:pk>', CircularUpdate.as_view(), name="Circular-update"),
    path('Circular/Delet/<int:pk>', CircularDelet.as_view(), name="Circular-delet"),
    
]

# Works

urlpatterns += [
    path('Works/create/', WorksCreate.as_view(), name="Works-create"),
    path('Works/List/', WorksList.as_view(), name="Works-list"),
    path('Works/Update/<int:pk>', WorksUpdate.as_view(), name="Works-update"),
    path('Works/Delet/<int:pk>', WorksDelet.as_view(), name="Works-delet"),
    
]

# Users

urlpatterns += [
    path('User/create/', UserCreate.as_view(), name="User-create"),
    path('User/List/', UserList.as_view(), name="User-list"),
    path('User/Update/<int:pk>', UserUpdate.as_view(), name="User-update"),
    path('User/Delet/<int:pk>', UserDelet.as_view(), name="User-delet"),
    path("logout/", views.LogoutView.as_view(), name="logout")
    
]

urlpatterns += [
    path('password_change/<int:pk>',password_recovery,name='password_change'),
    path('password_change/done/',password_change_done,name='password_change_done'),

]

# gallery

urlpatterns += [
    path('Gallery/images/WorkList/' , Work_Image_List.as_view() , name='Work_Image-List'),
    path('Gallery/images/CircularList/',Circular_Images_List.as_view() , name='Circular_Image-List')
]


# faq 

urlpatterns += [
    path('faq/List/', faqlist.as_view(), name="faq-list"),
    path('faq/create/', FaqCreate.as_view(), name="faq-create"),
    path('faq/Update/<int:pk>', faqUpdate.as_view(), name="faq-update"),
    path('faq/Delet/<int:pk>', faqDelet.as_view(), name="faq-delet")
]

# Handout


urlpatterns += [
    path('Handout/List/', HandoutList.as_view(), name="Handout-list"),
    path('Handout/create/', HandoutCreate.as_view(), name="Handout-create"),
    path('Handout/Update/<int:pk>', HandoutUpdate.as_view(), name="Handout-update"),
    path('Handout/Delet/<int:pk>', HandoutDelet.as_view(), name="Handout-delet")
]

# SectionChoice 

urlpatterns += [
    path('sectionchoice/List/', SectionChoice_list.as_view(), name="sectionchoice-list"),
    path('sectionchoice/Delete/<int:pk>', SectionChoice_Delet.as_view(), name="sectionchoice-delete")
]

urlpatterns += [
    path('picture/create/' , create_picture.as_view(),name="picture-create"),
    path('picture/list/' , picture_list.as_view(),name="picture-list"),
    path('picture/delete/<int:pk>' , delete_picture.as_view(),name="picture-delete"),
    
]

urlpatterns += [
    path('HomeInfo/List/', HomeInfoList.as_view(), name="HomeInfo-list"),
    path('HomeInfo/create/', HomeInfoCreate.as_view(), name="HomeInfo-create"),
    path('HomeInfo/Update/<int:pk>', HomeInfoUpdate.as_view(), name="HomeInfo-update"),
    path('HomeInfo/Delet/<int:pk>', HomeInfoDelet.as_view(), name="HomeInfo-delet")
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms import ModelForm

class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True)




class EditProfileForm(ModelForm):
    class Meta:
        model = User
        fields = (
                 'username',
                 'first_name',
                 'last_name',
                 'email',
                 'is_superuser',
                 'is_staff'
                )
        
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm



class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address')

    class Meta:
        model = User
        fields = [
            'username', 
            'first_name', 
            'last_name', 
            'email', 
            'password1', 
            'password2', 
            'is_superuser',
            'is_staff'
            ]
        
class ResetForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'off'}))
    password_confrim = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete': 'off'}))
    
    
class edit_userForm(forms.Form):
    email = forms.CharField(label="ایمیل جدید")
    username = forms.CharField(label="نام کاربری جدید")
    
from courses.models import *
    
class HandoutForm(forms.ModelForm):
    other_files = forms.FileField(required=False, label='فایل های دیگر جزوه')
    class Meta:
        model = Handout
        fields = '__all__'
        

class PictureForm(forms.Form):
    image = forms.ImageField()

users/views.py
from typing import Any, Optional
from django.db import models
from django.shortcuts import render,redirect, get_object_or_404
from .forms import LoginForm  ,SignUpForm , ResetForm ,edit_userForm
from django.contrib.auth import authenticate,login as auth_login
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.views.generic import CreateView, UpdateView, ListView, DeleteView
from django.contrib import messages
from .mixins import *
from notifications.models import Notification , Circular
from shopping.models import Works
from pictures.models import *
from gallery.models import Works_Images , Circular_Images
from courses.models import Faq , Handout
from django.contrib.auth.mixins import LoginRequiredMixin
from .serializers import *
from rest_framework.decorators import api_view , permission_classes
from rest_framework.permissions import IsAdminUser , IsAuthenticated
from rest_framework.exceptions import ParseError
from rest_framework.response import Response
from rest_framework.status import *
from rest_framework import generics
from django.utils.translation import gettext as _
from time import sleep




def home(request):
    slider_pictures = HomePictures.objects.all()
    recent_notifications = Notification.objects.all().order_by('-create_time')[:3]
    recent_works = Works.objects.all().order_by('-create_time')[:3]
    home_info = HomeInfo.objects.first()
    return render(request,'users/home.html',{
        'slider_pictures':slider_pictures , 
        'recent_notifications'  :recent_notifications,
        'recent_works': recent_works,
        'home_info' : home_info
    })




def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,username = cd['username'],password = cd['password'])
            if user is not None:
                if user.is_active:
                    auth_login(request,user)
                    for i in User.objects.filter(username = cd['username']):                
                        if i == user:
                            log_user = i
                        request.session['name'] = log_user.username
                        request.session['email'] = log_user.email
                        request.session['password'] = log_user.password
                        if log_user.is_staff == True or log_user.is_superuser == True:
                            return redirect('/User/Update/{}'.format(request.user.pk))
                        else:
                            return redirect('/auth/user/user_info/')
            else:
                message = messages.error(request, "نام کاربری یا رمز عبور نامعتبر است")
                return render(request,'users/login.html',{'message':message})

                
        else:
            form = LoginForm()
    else:
        form = LoginForm()
    return render(request,'users/login.html')




@login_required(login_url='/login/',redirect_field_name="/login/")
def user_information(request):
    name = request.session.get('name')
    email = request.session.get('email')
    if name == None :
        return redirect('/login/')
    return render(request,'users/user_informations.html',{
        'name':name,
        'email':email,
    })
    


class edit_info(LoginRequiredMixin, UpdateView):
    model = User
    success_url = '/login/'
    template_name = "users/edit_info.html"
    fields = [
        'username',
        'first_name',
        'last_name',
        'email',
    ]





@login_required(login_url='/login/')
def admin(request):
    return render(request,'users/adminlte.html')


# Notifications


class NotificationCreate(NotificationFiedsMixin, CreateView):
    model = Notification
    template_name = "users/notification-create.html"


class NotificationList(ListView, NotificationFiedsMixin):
    model = Notification
    template_name = "users/notification-list.html"

    ordering = ['-create_time']


class NotificationUpdate(NotificationFiedsMixin, UpdateView):
    model = Notification
    template_name = "users/notification-update.html"

class NotificationDelet(NotificationFiedsMixin, DeleteView):
    model = Notification
    success_url = reverse_lazy("users:notification-list")
    template_name = "users/notification_confirm_delete.html"
    
    
# Circulars

    
class CircularCreate(CircularFiedsMixin, CreateView):
    model = Circular
    success_url = reverse_lazy("users:Circular-list")
    template_name = "users/circular-create.html"


class CircularList(ListView, CircularFiedsMixin):
    model = Circular
    template_name = "users/circular-list.html"

    ordering = ['-create_time']


class CircularUpdate(CircularFiedsMixin, UpdateView):
    model = Circular
    success_url = reverse_lazy("users:Circular-list")
    template_name = "users/circular-update.html"

class CircularDelet(CircularFiedsMixin, DeleteView):
    model = Circular
    success_url = reverse_lazy("users:Circular-list")
    template_name = "users/circular_confirm_delete.html"
    

# Works

class WorksCreate(WorksFiedsMixin, CreateView):
    model = Works
    success_url = reverse_lazy("users:Works-list")
    template_name = "users/Works-create.html"


class WorksList(ListView, WorksFiedsMixin):
    model = Works
    template_name = "users/Works-list.html"




class WorksUpdate(WorksFiedsMixin, UpdateView):
    model = Works
    success_url = reverse_lazy("users:Works-list")
    template_name = "users/Works-update.html"

class WorksDelet(WorksFiedsMixin, DeleteView):
    model = Works
    success_url = reverse_lazy("users:Works-list")
    template_name = "users/Works_confirm_delete.html"
    


# Users


class UserCreate(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('users:User-list')
    template_name = 'users/User-create.html'


class UserList(ListView, UserFiedsMixin):
    model = User
    template_name = "users/User-list.html"




class UserUpdate(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy("users:User-list")
    template_name = "users/User-update.html"
    fields = [
        'username',
        'first_name',
        'last_name',
        'email',
        'is_staff',
        'is_superuser'
    ]


    def get_object(self , queryset = None):
        if  self.request.user.is_superuser:
            user = get_object_or_404(User , pk = self.kwargs['pk'])
        else:
            user = self.request.user
        return user




class UserDelet(UserFiedsMixin, DeleteView):
    model = User
    success_url = reverse_lazy("users:User-list")
    template_name = "users/User_confirm_delete.html"
    
    
def validate_new_password(new_password):
    try:
        validate_password(new_password)
        return True  
    except ValidationError as e:
        return False
    
@login_required(login_url='/login/')
def password_recovery(request ,pk ):
    error_reset = None
    if request.method == 'POST':
        form = ResetForm(request.POST)
        if form.is_valid():
            form_info = form.cleaned_data
            user_info = User.objects.get(pk = pk)
            if form_info['password'] == form_info['password_confrim']:
                if validate_new_password(form_info['password']):
                
                    new_password = form_info['password_confrim']
                    user_info.set_password(new_password)
                    user_info.save()
                    if request.user.pk == user_info.pk:
                        return redirect('/login/')
                    else:
                        return redirect('/password_change/done/')
                else:
                    error_reset = messages.error(request, "رمز عبور نامعتبر است")
            else:
                error_reset = messages.error(request, "رمز های عبور یکسان نیستند")                
                return render(request,'users/password_change.html',{
                'form':form,
                'error_reset':error_reset
                })
    else :
        form = ResetForm()
    return render(request,'users/password_change.html',{
        'form':form,
        })
    

def password_change_done(request):
    return render(request , 'users/password_done.html')
    

    
# Gallery
    
class Work_Image_List(ListView):
    model = Works_Images
    ordering = ['-pk']
    template_name = "users/Work_Images-list.html"
    

class Circular_Images_List(ListView):
    model = Circular_Images
    ordering = ['-pk']
    template_name = "users/Circular_Images-list.html"
    
# faq

class faqlist(ListView):
    model = Faq
    ordering = ['-create_time']
    template_name = "users/faq_list.html"

   
class FaqCreate(FaqFiedsMixin, CreateView):
    model = Faq
    success_url = reverse_lazy("users:faq-list")
    template_name = "users/faq-create.html"
 

class faqUpdate(FaqFiedsMixin, UpdateView):
    model = Faq
    success_url = reverse_lazy("users:faq-list")
    template_name = "users/faq-update.html"

class faqDelet(WorksFiedsMixin, DeleteView):
    model = Faq
    success_url = reverse_lazy("users:faq-list")
    template_name = "users/faq_confirm_delete.html"
    
    
    
# Hnadout

from .forms import *




class HandoutCreate(CreateView):
    model = Handout
    form_class = HandoutForm
    template_name = "users/Handout-create.html"
    success_url = reverse_lazy("users:Handout-list")

    def form_valid(self, form):
        # ابتدا فرم را ذخیره می‌کنیم تا نمونه Handout ایجاد شود
        response = super().form_valid(form)
        
        # ایجاد نمونه‌های File و ذخیره آن‌ها به همراه نمونه Handout مربوطه
        other_files_data = self.request.FILES.getlist('other_files')
        if other_files_data:
            for other_file_data in other_files_data:

users/templates/users/User-list.html
{% extends 'users/adminlte.html' %}

{% block title  %}لیست کاربر ها{% endblock %}

{% block content %}
{% if user.is_superuser%}
<div class="row">
    <div class="col-12">
      <div class="card">
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>نام</th>
                <th>نام خانوادگی</th>
                <th>نام کاربری</th>
                <th>آدرس ایمیل</th>
                <th>ویرایش یا حذف</th>
              </tr>
            </thead>
            <tbody>
                {% for user in object_list %}
                  <tr>
                    <td>
                      <a href="{% url 'users:User-update' user.pk %}"> {{user.first_name}}</a>
                    </td>
                      <td>{{user.last_name}}</td>
                      <td>{{user.username}}</td>
                      <td>{{user.email}}</td>
                      <td><a class="badge badge-primary" style="font-size: 13px;" href="{% url 'users:User-update' user.pk %}">ویرایش و حذف</a></td>
                  </tr>
                {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
  {% elif user.is_staff %}
  <div class="row">
    <div class="col-12">
      <div class="card">
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
          <table class="table table-hover">
            <thead>
              <tr>
                <th>نام</th>
                <th>نام خانوادگی</th>
                <th>نام کاربری</th>
                <th>آدرس ایمیل</th>
                <th>ویرایش یا حذف</th>
              </tr>
            </thead>
            <tbody>
                  <tr>
                    <td>
                      <a href="{% url 'users:User-update' user.pk %}"> {{user.first_name}}</a>
                    </td>
                      <td>{{user.last_name}}</td>
                      <td>{{user.username}}</td>
                      <td>{{user.email}}</td>
                      <td><a class="badge badge-primary" style="font-size: 13px;" href="{% url 'users:User-update' user.pk %}">ویرایش و حذف</a></td>
                  </tr>

                </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>

{%endif%}
{% endblock %}

users/templates/users/User-update.html
{% extends 'users/adminlte.html' %}
{% load crispy_forms_tags %}

{% block title %}
ویرایش کاربر
{%endblock%}
{% block content %}
    <div class="col-md-12">
        <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title mb-0 float-left">ویرایش کاربر</h3>
        </div>
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-6">
                            {{form.username|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{form.first_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{form.last_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{form.email|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0" style="display: -webkit-inline-box!important;">
                            <a class="btn btn-danger"  href="{% url 'users:password_change' user.pk %}" target="_blank" rel="noopener noreferrer">برای بازیابی گذرواژه اینجا کلیک کنید</a>
                        </div>
                        {%if request.user.is_superuser %}
                        <div class="form-group col-md-6 mb-0">
                            {{form.is_superuser|as_crispy_field }}
                        </div>
                        {%endif%}
                        <div class="form-group col-md-6 mb-0">
                            {{form.is_staff|as_crispy_field }}
                        </div>
                        <br><br>
                    </div>
                    <div style="margin-bottom: 15px; display: flex; justify-content: center;" >
                    <input type="submit" style="width: 49%; margin-left: 1%;" value="ویرایش کاربر" class="btn btn-success">
                    <a class="btn btn-danger" style="width: 49%;" href="{% url 'users:User-delet' user.pk %}">حذف کاربر</a>
                </div>
            </form>
    </div>

{% endblock %}

users/templates/users/sate-bar.html
  {% load static %}
  
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4" style="text-align: start;">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="{% static 'admin-lte/dist/img/logo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">هنرستان خواجه نصیر</span>
    </a>
  
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'admin-lte/dist/img/avatar5.png' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{request.user.get_full_name}}</a>
        </div>
      </div>
  
      <!-- Sidebar Menu -->
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false" style="padding-right: 0;">
        <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              بخش انتشار
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'users:notification-list' %}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>اطلاعیه ها</p>
                <span class="right badge badge-primary">لیست اطلاعیه</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'users:notification-create' %}" class="nav-link">
                <i class="fa fa-edit nav-icon"></i>
                <p>اطلاعیه ها</p>
                <span class="right badge badge-success">افزودن اطلاعیه</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'users:Circular-list'%}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>بخش نامه ها</p>
                <span class="right badge badge-primary">لیست بخشنامه</span>
              </a>
            </li>
            {% if request.user.is_superuser %}
            <li class="nav-item">
              <a href="{% url 'users:Circular-create'%}" class="nav-link">
                <i class="fa fa-edit nav-icon"></i>
                <p>بخش نامه ها</p>
                <span class="right badge badge-success">افزودن بخشنامه</span>
              </a>
            </li>
            {% endif %}
          </ul>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              نمونه کار ها
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'users:Works-list' %}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>نمونه کار ها</p>
                <span class="right badge badge-primary">لیست نمونه کار</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'users:Works-create' %}" class="nav-link">
                <i class="fa fa-edit nav-icon"></i>
                <p>نمونه کار ها</p>
                <span class="right badge badge-success">افزودن نمونه کار</span>
              </a>
            </li>
          </ul>
        </li>
        
        {% if request.user.is_superuser %}
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              کنترل کاربر ها
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'users:User-list' %}" class="nav-link">
                <i class="fa fa-users nav-icon"></i>
                <p>کاربر ها</p>
                <span class="right badge badge-primary">لیست کاربر</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'users:User-create' %}" class="nav-link">
                <i class="fa fa-users nav-icon"></i>
                <p>کاربر ها</p>
                <span class="right badge badge-success">افزودن کاربر</span>
              </a>
            </li>
          </ul>
        </li>
        {% endif %}
        {% if request.user.is_superuser %}
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              گالری تصاویر
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'users:Circular_Image-List' %}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>تصاویر بخشنامه ها</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'users:Work_Image-List' %}" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>تصاویر نمونه کار ها</p>
              </a>
            </li>
          </ul>
          {% endif %}
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                سوالات و جزوه ها
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'users:faq-list' %}" class="nav-link">
                  <i class="fa fa-list nav-icon"></i>
                  <p>سوالات</p>
                  <span class="right badge badge-primary">لیست سوالات</span>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'users:faq-create' %}" class="nav-link">
                  <i class="fa fa-edit nav-icon"></i>
                  <p>سوالات</p>
                  <span class="right badge badge-success">افزودن سوال</span>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'users:Handout-list' %}" class="nav-link">
                  <i class="fa fa-list nav-icon"></i>
                  <p>جزوه ها</p>
                  <span class="right badge badge-primary">لیست جزوه ها</span>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'users:Handout-create'%}" class="nav-link">
                  <i class="fa fa-edit nav-icon"></i>
                  <p>جزوه ها</p>
                  <span class="right badge badge-success">افزودن جزوه ها</span>
                </a>
              </li>
            </ul>
          </li>
        </li>
        {% if request.user.is_superuser %}
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              رشته ها
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="/sectionchoice/List/" class="nav-link">
                <i class="fa fa-list nav-icon"></i>
                <p>رشته ها</p>
                <span class="right badge badge-primary">لیست رشته ها</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="/sections/handout/create/" class="nav-link">
                <i class="fa fa-edit nav-icon"></i>
                <p>رشته ها</p>
                <span class="right badge badge-success">افزودن رشته</span>
              </a>
            </li>

          </ul>
          {% endif %}
          {% if request.user.is_superuser %}
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                اطلاعات هنرستان
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="/picture/list/" class="nav-link">
                  <i class="fa fa-list nav-icon"></i>
                  <p>تصاویر</p>
                  <span class="right badge badge-primary">لیست تصاویر</span>
                </a>
              </li>
              <li class="nav-item">
                <a href="/picture/create/" class="nav-link">
                  <i class="fa fa-edit nav-icon"></i>
                  <p>تصاویر</p>
                  <span class="right badge badge-success">افزودن تصویر</span>
                </a>
              </li>


              <li class="nav-item">
                <a href="/HomeInfo/List/" class="nav-link">
                  <i class="fa fa-list nav-icon"></i>
                  <p>اطلاعات کلی</p>
                  <span class="right badge badge-primary">مشاهده</span>
                </a>
              </li>
              <li class="nav-item">
                <a href="/HomeInfo/create/" class="nav-link">
                  <i class="fa fa-edit nav-icon"></i>
                  <p>افزودن اطلاعات</p>
                  <span class="right badge badge-danger">تنها یک بار</span>
                </a>
              </li>
  
            </ul>
            {% endif %}
        </li>
      </li>
      </ul>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>
  